name: actualizar directorio cada 4 horas
on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://api-torii.up.railway.app/api/anime/directory/update' \
